const { ROLES } = require("./roles");
const { PERMISSIONS } = require("./permissions");

const roleDefaultPermissions = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PARENT]: [
    PERMISSIONS.KIDS_READ,
    PERMISSIONS.KIDS_WRITE,
    PERMISSIONS.PICTOGRAMS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.SCENARIOS_READ,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.HISTORY_WRITE,
    PERMISSIONS.SESSIONS_READ,
    PERMISSIONS.SESSIONS_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ].filter(Boolean),
  [ROLES.THERAPIST]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.KIDS_READ,
    PERMISSIONS.KIDS_WRITE,
    PERMISSIONS.PICTOGRAMS_READ,
    PERMISSIONS.PICTOGRAMS_WRITE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.CATEGORIES_WRITE,
    PERMISSIONS.SCENARIOS_READ,
    PERMISSIONS.SCENARIOS_WRITE,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.HISTORY_WRITE,
    PERMISSIONS.SESSIONS_READ,
    PERMISSIONS.SESSIONS_WRITE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.CHILD]: [
    PERMISSIONS.KIDS_READ,
    PERMISSIONS.PICTOGRAMS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.SCENARIOS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.HISTORY_WRITE,
    PERMISSIONS.SESSIONS_READ,
    PERMISSIONS.SESSIONS_WRITE,
    PERMISSIONS.AI_USE,
  ],
};

module.exports = { roleDefaultPermissions };
